module_OOP
Yarik192/module_OOP_ pull request #1
Opened 2021-12-15 15:25 UTC by Yarik192

2021-12-15 16:22 UTC, sgorodilov reviewed
All loops require a refactoring.
The `Player.defence` method has unexpected side-effects.
This works as a miracle.

2021-12-15 16:22 UTC, shorodilov commented on models.py
> +
This should really be moved into the game engine. The `models` module has no responsibility for this stuff.

2021-12-15 16:22 UTC, shorodilov commented on models.py
> +        score.write(f"Player - {player_obj.name}, scored: {player_obj.score} points\n")
Move this functions to the `game` module.

2021-12-15 16:22 UTC, shorodilov commented on settings.py
> +
Do not include functions into `constants` unless their help is needed.

2021-12-15 16:22 UTC, sgorodilov commented on models.py
> +        if self.lives != 1:
Let assume `lives` value is set to `0`, this may become a problem.

2021-12-15 16:22 UTC, sgorodilov commented on models.py
> +        while True:
Do we actually need this endless-loop here?

2021-12-15 16:22 UTC, sgorodilov commented on models.py
> +        while True:
Do we actually need this endless-loop here.

2021-12-15 16:22 UTC, sgorodilov commented on models.py
> +        if self.lives != 0:
That if `lives` value is set to `0`?

2021-12-15 16:22 UTC, sgorodilov commented on models.py
> +from settings import LIVES, exodus_1, exodus_2, rules
Do we need `rules` import here?

2021-12-15 16:22 UTC, sgorodilov commented on models.py
> +                self.decrease_lives()
Not included into requirements

2021-12-15 16:22 UTC, sgorodilov commented on models.py
> +        continue
I'll get the same behavior without this line.

2021-12-15 16:22 UTC, sgorodilov commented on models.py
> +    rules()
Does this expected?

2021-12-15 16:22 UTC, sgorodilov commented on models.py
> +    user_name = input("Enter your name: ")
No `user_name` validation. We should really check it's correct.

2021-12-15 16:22 UTC, sgorodilov commented on exeptions.py
> +class Exit(Exception):
This one is useless, just remove it since you're not going to use it in any of your modules.

2021-12-15 16:27 UTC, sgorodilov commented on models.py
> +        if self.lives != 1:
It's about `continue` in the end of the loop-block

2021-12-15 18:09 UTC, sgorodilov requested changes
The program implementations has side-effects which should be fixed.
While loops should be reviewed.

2021-12-15 18:09 UTC, shorodilov commented on models.py
> +        if self.lives > 0:
Just use `self.lives -= 1` and perform positive validation as `if self.lives < 1`

2021-12-15 18:09 UTC, shorodilov commented on models.py
> +            self.score += 1
Do not include the most expected behavior into `else` block. Move it to `if`.

2021-12-15 18:09 UTC, shorodilov commented on models.py
> +            self.score += 1
This method has a score-change side-effect which is not described in the original scope.
As well move the most expected behavior to the `if` block, do not hide it down side.

2021-12-15 18:09 UTC, shorodilov commented on models.py
> +            rules()
Remove all the unused logics. It a trash functions without any useful payload.

2021-12-15 18:09 UTC, shorodilov commented on models.py
> +            return user_name.capitalize()
Why it should be capitalized?

2021-12-15 18:09 UTC, shorodilov commented on models.py
> +        if len(user_name) > 2 and user_name.isalpha():
Why it should be 3-characters long? I'd like it to be 5 or more chars.

2021-12-15 18:09 UTC, sgorodilov commented on models.py
> +def rules():
Why this is implemented within `models`?

2021-12-15 18:09 UTC, sgorodilov commented on models.py
> +def check_name():
Why this is implemented with `models` module?

2021-12-15 18:09 UTC, sgorodilov commented on game.py
> +            def get_scores(player_obj: Player) -> None:
And... that if just delete the inner function and handle score-write without it?

2021-12-16 14:00 UTC, sgorodilov approved these changes
There are few issues and output text is non informative.
But it will work in a specif cases.

2021-12-16 14:00 UTC, shorodilov commented on game.py
> +    if choice == "start":
Move out from the function. This will break the logic and potentially will raise an exception.

2021-12-16 14:00 UTC, shorodilov commented on models.py
> +            self.score += 1
Score assignment is unexpected.

2021-12-16 14:00 UTC, shorodilov commented on game.py
> +def get_scores(player_obj: Player) -> None:
This should be called `write_scores`

2022-04-26 18:35 UTC, merged